language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'CREATE DATABASE momoko_test;' -U postgres
  - psql -U postgres momoko_test -c 'CREATE EXTENSION IF NOT EXISTS hstore'
  - make -C tcproxy
  - env

env:
  global:
    - MOMOKO_TEST_HSTORE=1
    - MOMOKO_TEST_JSON=1
    - MOMOKO_TEST_HOST=127.0.0.1
    - PGHOST=127.0.0.1
  matrix:
    - MOMOKO_PSYCOPG2_IMPL=psycopg2
    - MOMOKO_PSYCOPG2_IMPL=psycopg2cffi

install: "pip install tornado ${MOMOKO_PSYCOPG2_IMPL} unittest2"
script: python setup.py test

matrix:
  exclude:
    - python: pypy
      env: MOMOKO_PSYCOPG2_IMPL=psycopg2
