language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

before_script:
  - psql -c 'CREATE DATABASE momoko_test;' -U postgres

env:
  - MOMOKO_PSYCOPG2_IMPL=psycopg2
  - MOMOKO_PSYCOPG2_IMPL=psycopg2ct
  - MOMOKO_PSYCOPG2_IMPL=psycopg2cffi

install: "pip install --use-mirrors coveralls tornado ${MOMOKO_PSYCOPG2_IMPL}"
script: coverage run --source=momoko setup.py test
after_success: coveralls

matrix:
  exclude:
    - python: 3.2
      env: MOMOKO_PSYCOPG2_IMPL=psycopg2ct
    - python: 3.2
      env: MOMOKO_PSYCOPG2_IMPL=psycopg2cffi
    - python: 3.3
      env: MOMOKO_PSYCOPG2_IMPL=psycopg2ct
    - python: 3.3
      env: MOMOKO_PSYCOPG2_IMPL=psycopg2cffi
    - python: pypy
      env: MOMOKO_PSYCOPG2_IMPL=psycopg2

      # Doesn't work on Travis CI
    - python: pypy
      env: MOMOKO_PSYCOPG2_IMPL=psycopg2cffi
